filmovi_projekt/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from main import views

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    #path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('login/', views.login_view, name='login'),
    path('logged/', views.logged_in, name='logged_in'),
    path('logout/', views.logout_view, name='logout_view'),
]

main/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from .views import (
    MovieListView, MovieDetailView,
    ReviewListView, ReviewDetailView,
    toggle_like, ReviewUpdateView, MovieRecommendationUpdateView, MovieRecommendationDetailView, ReviewViewSet, MovieListAPIView
)

app_name = 'main'  # here for namespacing of urls.

router = DefaultRouter()
router.register(r'reviews', ReviewViewSet, basename='review')

urlpatterns = [
    path('', views.index, name='index'),
    path('movies/', MovieListView.as_view(), name='movie_list'),
    path('movies/<int:pk>/', MovieDetailView.as_view(), name='movie_detail'),
    path('reviews_detail/', ReviewListView.as_view(), name='review_list'),
    path('reviews_detail/<int:pk>/', ReviewDetailView.as_view(), name='review_detail'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout_view'),
    path('logged/', views.logged_in, name='logged_in'),
    path('reviews/', views.reviews, name='reviews'),
    path('toggle_like/<int:movie_id>/', toggle_like, name='toggle_like'),
    path('reviews/update/<int:pk>/', ReviewUpdateView.as_view(), name='review_update'),
    path('recommendations/update/<int:pk>/', MovieRecommendationUpdateView.as_view(), name='movie_recommendation_update'),
    path('recommendations/<int:pk>/', MovieRecommendationDetailView.as_view(), name='movie_recommendation_detail'),
    path('reviews/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review_delete'),
    path('recommendations/delete/<int:pk>/', views.MovieRecommendationDeleteView.as_view(), name='movie_recommendation_delete'),
    path('api/', include(router.urls)),
    path('api/movies/', MovieListAPIView.as_view(), name='api_movies'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_date = models.DateField()
    genre = models.CharField(max_length=100)
    description = models.TextField()
    director = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    rating = models.PositiveSmallIntegerField()  
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.movie.title} - {self.rating}/10"


class UserMovie(models.Model):
    user = models.ForeignKey(User, related_name='liked_movies', on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, related_name='liked_by_users', on_delete=models.CASCADE)
    liked = models.BooleanField(default=False)

    def __str__(self):
        return f"User '{self.user}', movie '{self.movie}' - Liked: '{self.liked}'"


class UserRecommendation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    movie = models.OneToOneField(Movie, on_delete=models.CASCADE)
    reason = models.TextField()

    def __str__(self):
        return f"Recommendation for {self.user.username} - {self.movie.title}"


class MovieRecommendation(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='movie_recommendations')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_recommendations')
    reason = models.TextField()

    def __str__(self):
        return f"Recommendation for {self.movie.title} by {self.user.username}"

main/forms.py
from django import forms
from main.models import Review, MovieRecommendation


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['movie', 'rating', 'comment']
        widgets = {
            'movie': forms.Select(attrs={'class': 'form-control'}),
            'rating': forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'max': 10}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }


class RecommendationForm(forms.ModelForm):
    class Meta:
        model = MovieRecommendation
        fields = ['movie', 'reason']
        widgets = {
            'movie': forms.Select(attrs={'class': 'form-control'}),
            'reason': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .models import Movie, UserMovie, UserRecommendation, Review, MovieRecommendation
from main.forms import ReviewForm, RecommendationForm
from django.views.generic import ListView, DetailView, DeleteView
from django.views.generic.edit import UpdateView
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from .serializers import ReviewSerializer
from rest_framework.generics import ListAPIView
from .serializers import MovieSerializer

# Create your views here.

class MovieListAPIView(ListAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer
    permission_classes = [IsAuthenticated]  


class ReviewViewSet(viewsets.ModelViewSet):
    queryset = Review.objects.all()
    serializer_class = ReviewSerializer
    permission_classes = [IsAuthenticated]

    """ Za prikazivanje samo komentara ulogiranog korisnika
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)
    """
    

    def perform_create(self, serializer):
        # Automatski postavljamo korisnika kao autora recenzije
        serializer.save(user=self.request.user)


# Brisanje preporuka
class MovieRecommendationDeleteView(LoginRequiredMixin, DeleteView):
    model = MovieRecommendation
    template_name = 'main/movie_recommendation_confirm_delete.html'
    context_object_name = 'recommendation'
    success_url = reverse_lazy('main:reviews')  # Preusmjeravanje na popis preporuka nakon brisanja

    def get_queryset(self):
        # samo korisnici koji su dali preporuku mogu je obrisati
        return self.model.objects.filter(user=self.request.user)


# Brisanje recenzija
class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'main/review_confirm_delete.html'
    context_object_name = 'review'
    success_url = reverse_lazy('main:review_list')  # Preusmjeravanje na popis recenzija nakon brisanja

    def get_queryset(self):
        # samo korisnici koji su napisali recenziju mogu je obrisati
        return self.model.objects.filter(user=self.request.user)
    

class MovieRecommendationUpdateView(UpdateView):
    model = MovieRecommendation
    template_name = 'main/movie_recommendation_update.html'
    fields = ['reason']  # Polje koje korisnik može ažurirati
    context_object_name = 'recommendation'

    def test_func(self):
        # Provjera da li je korisnik vlasnik recenzije
        return self.request.user == self.get_object().user


    def get_success_url(self):
        # Preusmjeravanje na DetailView ažuriranog objekta
        return reverse('main:movie_recommendation_detail', kwargs={'pk': self.object.pk})

class ReviewUpdateView(UpdateView):
    model = Review
    template_name = 'main/review_update.html'
    fields = ['rating', 'comment']  # Polja koja korisnik može ažurirati
    

    def test_func(self):
        # Provjera da li je korisnik vlasnik recenzije
        return self.request.user == self.get_object().user

    def get_success_url(self):
        # Preusmjeravanje na DetailView ažuriranog objekta
        return reverse('main:review_detail', kwargs={'pk': self.object.pk})
    


# ListView za Movie s pretraživanjem
class MovieListView(ListView):
    model = Movie
    template_name = 'main/movie_list.html'
    context_object_name = 'movies'

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('q', '')
        genre_filter = self.request.GET.get('genre', '')
        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query) | Q(genre__icontains=search_query)
            )
        if genre_filter:
            queryset = queryset.filter(genre__icontains=genre_filter)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Movie.objects.values_list('genre', flat=True).distinct()
        return context

# DetailView za Movie
class MovieDetailView(DetailView):
    model = Movie
    template_name = 'main/movie_detail.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = self.object.reviews.all()  # Prikazivanje svih recenzija za ovaj film
        context['movie_recommendations'] = self.object.movie_recommendations.all()  # Prikazivanje svih preporuka za ovaj film
        if self.request.user.is_authenticated:
            # Provjeri je li korisnik lajkao film
            liked = UserMovie.objects.filter(
                user=self.request.user, movie=self.object, liked=True
            ).exists()
            context['liked'] = liked
        else:
            context['liked'] = False
        return context

# ListView za Review s pretraživanjem i filtriranjem po korisniku
class ReviewListView(ListView):
    model = Review
    template_name = 'main/review_list.html'
    context_object_name = 'reviews_detail'

    def get_queryset(self):
        queryset = super().get_queryset()
        user_filter = self.request.GET.get('user', '')
        if user_filter:
            queryset = queryset.filter(user__username__icontains=user_filter)
        return queryset

# DetailView za recenzije
class ReviewDetailView(DetailView):
    model = Review
    template_name = 'main/review_detail.html'
    context_object_name = 'review'

    
def index(request):
    return render(request, 'main/index.html')

#DetailView za preporuke
class MovieRecommendationDetailView(DetailView):
    model = MovieRecommendation
    template_name = 'main/movie_recommendation_detail.html'
    context_object_name = 'recommendation'

# pogled za login
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)  # Prijavljuje korisnika
            return redirect('logged_in')  # na logged_in stranicu nakon prijave
    else:
        form = AuthenticationForm()

    return render(request, 'main/login.html', {'form': form})

# pogled za logout
def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def logged_in(request):
    """
    Funkcionalnost za prikazivanje logged.html
    Samo prijavljeni korisnici mogu pristupiti ovoj stranici.
    """
    movies = Movie.objects.all()
    liked_movies = UserMovie.objects.filter(user=request.user, liked=True).select_related('movie')
    user_recommendations = UserRecommendation.objects.filter(user=request.user).select_related('movie')  # Preporuke za korisnika

    return render(request, 'main/logged.html', {
        'all_movies': movies,
        'liked_movies': liked_movies,
        'user_recommendations': user_recommendations,
    }) 

@login_required
def reviews(request):
    """
    Dohvat svih recenzija i preporuka za trenutnog korisnika.
    """
    # Dohvati sve recenzije iz baze
    reviews = Review.objects.all()
    
    # Dohvati sve preporuke za trenutnog korisnika
    movie_recommendations = MovieRecommendation.objects.all()

    # Ako se podaci šalju preko POST-a, obrađujemo ih
    if request.method == 'POST':
        if 'submit_review' in request.POST:
            review_form = ReviewForm(request.POST)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.user = request.user
                review.save()
                return redirect('main:reviews')
        else:
            review_form = ReviewForm()
        
        if 'submit_recommendation' in request.POST:
            recommendation_form = RecommendationForm(request.POST)
            if recommendation_form.is_valid():
                recommendation = recommendation_form.save(commit=False)
                recommendation.user = request.user
                recommendation.save()
                return redirect('main:reviews')
        else:
            recommendation_form = RecommendationForm()
    else:
        review_form = ReviewForm()
        recommendation_form = RecommendationForm()

    return render(request, 'main/reviews.html', {
        'reviews': reviews,
        'movie_recommendations': movie_recommendations,
        'review_form': review_form,
        'recommendation_form': recommendation_form,
    })

@login_required
def toggle_like(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    user_movie, created = UserMovie.objects.get_or_create(user=request.user, movie=movie)

    # If liked unlike, else (unliked) like
    if user_movie.liked:
        user_movie.liked = False
    else:
        user_movie.liked = True

    user_movie.save()
    return redirect('main:movie_detail', pk=movie_id)

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Početna stranica</title>
    
</head>
<body>
    
    <h1> Početna stranica </h1>
    <p></p>
    
    <a href="{% url 'login' %}">Prijava</a>
    
    <br>
    <br>
    <hr>
    <br>
    
    <a href="{% url 'admin:index' %}">Prijava administratora</a>
    

</body>
</html>

main/templates/main/logged.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}">
    <title>Dobrodošli!</title>
</head>

<body>
    <h1>Dobrodošli, {{ user.username }}!</h1>
    <p>Prijavljeni ste.</p>
    <div class="button-container">
        <a href="{% url 'main:movie_list' %}">Pretraga filmova</a>
        <a href="{% url 'main:reviews' %}">Pogledajte recenzije i preporuke</a>
        <a href="{% url 'main:logout_view' %}">Odjava</a>
    </div>
    
    <h2>Preporučeni filmovi:</h2>
    {% if user_recommendations %}
    <ul>
        {% for recommendation in user_recommendations %}
        <li>
            <strong>{{ recommendation.movie.title }}</strong> ({{ recommendation.movie.release_date|date:"Y" }}) -
            {{ recommendation.movie.genre }}<br>
            Razlog: {{ recommendation.reason }}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Trenutno nema preporuka za vas.</p>
    {% endif %}

    <hr>

    <h2>Popis filmova:</h2>
    <ul>
        {% for movie in all_movies %}
        <li>
            <strong>{{ movie.title }}</strong> ({{ movie.release_date|date:"Y" }})<br>
            Žanr: {{ movie.genre }}<br>
            Redatelj: {{ movie.director }}<br>
            Opis: {{ movie.description }}
            <br>
            <br>
        </li>
        {% empty %}
        <p>Nema dostupnih filmova u bazi podataka.</p>
        {% endfor %}
    </ul>

    <hr>

    <h2>Filmovi koji vam se sviđaju:</h2>
    {% if liked_movies %}
    <ul>
        {% for user_movie in liked_movies %}
        <li>{{ user_movie.movie.title }} ({{ user_movie.movie.release_date|date:"Y" }}) </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Nema lajkanih filmova.</p>
    {% endif %}

    

</body>

</html>

main/templates/main/login.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>

    <br>
    <a href="{% url 'main:index' %}">Početna stranica</a>
    
</body>
</html>

main/templates/main/movie_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style5.css' %}">
    <title>{{ movie.title }}</title>
</head>
<body>
    <br>
    <hr>
    <a href="{% url 'main:movie_list' %}">Povratak na popis</a>
    <hr>
    
    <h1>{{ movie.title }}</h1>
    
    <p><strong>Žanr:</strong> {{ movie.genre }}</p>
    <p><strong>Datum izlaska:</strong> {{ movie.release_date }}</p>
    <p><strong>Redatelj:</strong> {{ movie.director }}</p>
    <p><strong>Opis:</strong> {{ movie.description }}</p>

    {% if user.is_authenticated %}
        <!-- Like gumb -->
        <form method="post" action="{% url 'main:toggle_like' movie.id %}">
            {% csrf_token %}
            {% if liked %}
                <button class="unlike" type="submit">Unlike</button>
            {% else %}
                <button type="submit">Like</button>
            {% endif %}
        </form>
    {% else %}
        <p><a href="{% url 'login' %}">Prijavi se za lajkanje.</a></p>
    {% endif %}
    
    <br>
    <hr>
    <h2>Recenzije</h2>
    {% if reviews %}
        <ul>
            {% for review in reviews %}
                <li>
                    <strong>Korisnik:</strong> {{ review.user.username }} <br>
                    <strong>Ocjena:</strong> {{ review.rating }}/10 <br>
                    <strong>Komentar:</strong> {{ review.comment }} <br>
                    <strong>Datum:</strong> {{ review.created_at }}<br><br>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nema recenzija za ovaj film.</p>
    {% endif %}
    <br>
    <hr>
    <h2>Preporuke za film</h2>
    {% if movie_recommendations %}
        <ul>
            {% for rec in movie_recommendations %}
                <li>
                    <strong>Korisnik:</strong> {{ rec.user.username }} <br>
                    <strong>Razlog:</strong> {{ rec.reason }}<br><br>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nema preporuka za ovaj film.</p>
    {% endif %}
</body>
</html>

main/templates/main/movie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style3.css' %}">
    <title>Popis Filmova</title>
</head>
<body>
    <br>
    
    <a class="povratak" href="{% url 'main:logged_in' %}">Povratak</a>
    
    <h1>Popis Filmova</h1>
    <form method="get" action="{% url 'main:movie_list' %}">
        <input type="text" name="q" placeholder="Pretraži filmove..." value="{{ request.GET.q }}">
        <button type="submit">Pretraži</button>
        <select name="genre">
            <option value="">Svi žanrovi</option>
            {% for genre in genres %}
                <option value="{{ genre }}" {% if request.GET.genre == genre %}selected{% endif %}>
                    {{ genre }}
                </option>
            {% endfor %}
        </select>
        <button type="submit">Filtriraj</button>
    </form>
    
    <ul>
        {% for movie in movies %}
            <li>
                <a href="{% url 'main:movie_detail' movie.pk %}">{{ movie.title }}</a> ({{ movie.release_date }})
            </li>
        {% endfor %}
    </ul>
    {% if not movies %}
        <p>Nema dostupnih filmova.</p>
    {% endif %}
</body>
</html>

main/templates/main/movie_recommendation_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style3.css' %}">
    <title>Detalji Preporuke</title>
</head>
<body>
<h1>Potvrdite brisanje preporuke</h1>
<p>Želite li zaista obrisati ovu preporuku?</p>

<form method="post">
    {% csrf_token %}
    <button class="brisanje" type="submit">Da, obriši preporuku</button>
    <a href="{% url 'main:reviews' %}">Odustani</a>
</form>

</body>
</html>

main/templates/main/movie_recommendation_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style5.css' %}">
    <title>Detalji Preporuke</title>
</head>
<body>
    <h1>Preporuka za film: {{ recommendation.movie.title }}</h1>
    <p><strong>Korisnik:</strong> {{ recommendation.user.username }}</p>
    <p><strong>Razlog preporuke:</strong> {{ recommendation.reason }}</p>
    <p><strong>Film:</strong> {{ recommendation.movie.title }}</p>
    <a href="{% url 'main:reviews' %}">Povratak na popis recenzija i preporuka</a> <br>
    <br>
    {% if user == recommendation.user %} <!-- Provjera da li je korisnik vlasnik preporuke -->
        <a href="{% url 'main:movie_recommendation_update' recommendation.pk %}">Ažuriraj preporuku</a>
    {% endif %}
</body>
</html>

main/templates/main/movie_recommendation_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style6.css' %}">
    <title>Ažuriraj preporuku</title>
</head>
<body>
    <h1>Ažuriraj preporuku za "{{ recommendation.movie.title }}"</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Spremi promjene</button>
    </form>
    <br>
    <a href="{% url 'main:movie_recommendation_detail' recommendation.pk %}">Detalji preporuke</a>
</body>
</html>

main/templates/main/review_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style3.css' %}">
    <title>Detalji Recenzije</title>
</head>
<body>

<h1>Potvrdite brisanje recenzije</h1>
<p>Želite li zaista obrisati ovu recenziju?</p>

<form method="post">
    {% csrf_token %}
    <button class="brisanje" type="submit">Da, obriši recenziju</button>
    <br>
    <a href="{% url 'main:reviews' %}">Odustani</a>
</form>

</body>

main/templates/main/review_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style5.css' %}">
    <title>Detalji Recenzije</title>
</head>
<body>
    <br>
    <hr>
    <a href="{% url 'main:review_list' %}">Povratak na popis recenzija</a>
    <hr>

    <h1>Recenzija za "{{ review.movie.title }}"</h1>
    <p><strong>Korisnik:</strong> {{ review.user.username }}</p>
    <p><strong>Ocjena:</strong> {{ review.rating }}/10</p>
    <p><strong>Komentar:</strong> {{ review.comment }}</p>
    <p><strong>Datum:</strong> {{ review.created_at }}</p>
    <hr>
    <h2>Detalji o filmu</h2>
    <p><strong>Žanr:</strong> {{ review.movie.genre }}</p>
    <p><strong>Datum izlaska:</strong> {{ review.movie.release_date }}</p>
    <p><strong>Režiser:</strong> {{ review.movie.director }}</p>
    <p><strong>Opis:</strong> {{ review.movie.description }}</p>
</body>
</html>

main/templates/main/review_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style3.css' %}">
    <title>Popis Recenzija</title>
</head>
<body>
    <br>
   
    <a class="povratak" href="{% url 'main:reviews' %}">Povratak</a><br>
   
    <h1>Popis Recenzija</h1>
    <form method="get" action="{% url 'main:review_list' %}">
        <input type="text" name="user" placeholder="Pretraži po korisniku..." value="{{ request.GET.user }}">
        <button type="submit">Filtriraj</button>
    </form>
    <ul>
        {% for review in reviews_detail %}
            <li>
                <a href="{% url 'main:review_detail' review.pk %}">{{ review.movie.title }}</a> - {{ review.user.username }}: {{ review.rating }}/10
                {% if user == review.user %} <!-- Provjera da li je korisnik vlasnik recenzije -->
                     <a class="botun" href="{% url 'main:review_update' pk=review.pk %}">Ažuriraj</a>
                {% endif %}
                {% if review.user == user %}
                        <a class="botun" href="{% url 'main:review_delete' pk=review.pk %}">Obriši recenziju</a>
                    {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if not reviews_detail %}
        <p>Nema dostupnih recenzija.</p>
    {% endif %}
</body>
</html>

main/templates/main/review_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style6.css' %}">
    <title>Ažuriraj recenziju</title>
</head>
<body>
    <h1>Ažuriraj recenziju za "{{ review.movie.title }}"</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Spremi promjene</button>
    </form>
    <br>
    <a href="{% url 'main:reviews' %}">Povratak na popis recenzija</a>
</body>
</html>

main/templates/main/reviews.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style4.css' %}">
    <title>Recenzije i Preporuke</title>
</head>
<body>
    <h1>Recenzije</h1>
    <div class="button-container">
        <a href="{% url 'main:logged_in' %}">Povratak na početnu stranicu</a>
        <a href="{% url 'main:review_list' %}">Pretraga recenzija</a>
    </div>
    
    
    {% if reviews %}
        <ul>
            {% for review in reviews %}
                <li>
                    <strong>{{ review.movie.title }}</strong><br>
                    Korisnik: {{ review.user.username }}<br>
                    Ocjena: <strong>{{ review.rating }} / 10</strong><br>
                    Komentar: {{ review.comment }}<br>
                    {% if user == review.user %} <!-- Provjera da li je korisnik vlasnik recenzije -->
                         <a href="{% url 'main:review_update' pk=review.pk %}">Ažuriraj</a>
                    {% endif %}
                    {% if review.user == user %}
                        <a href="{% url 'main:review_delete' pk=review.pk %}">Obriši recenziju</a>
                    {% endif %}
                </li>
                <br>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nema recenzija u bazi.</p>
    {% endif %}

    <hr>


    <h2>Unos recenzije</h2>
    <form method="POST">
        {% csrf_token %}
        {{ review_form.as_p }}
        <button type="submit" name="submit_review">Pošalji recenziju</button>
    </form>

    <hr>
    
    <h1>Preporuke korisnika</h1>
    {% if movie_recommendations %}
        <ul>
            {% for recommendation in movie_recommendations %}
                <li>
                    <strong>{{ recommendation.movie.title }} by {{recommendation.user.username}}</strong> - 
                    {{ recommendation.reason }}<br>
                    {% if user == recommendation.user %} <!-- Provjera da li je korisnik vlasnik preporuke -->
                        <a href="{% url 'main:movie_recommendation_update' recommendation.pk %}">Ažuriraj preporuku</a>
                    {% endif %}
                    {% if recommendation.user == user %}
                        <a href="{% url 'main:movie_recommendation_delete' pk=recommendation.pk %}">Obriši preporuku</a>
                    {% endif %}
                    
                </li>
                <br>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nemate specifičnih preporuka.</p>
    {% endif %}
    
    <br>
    <hr>

    <h2>Unos preporuka</h2>
    <form method="POST">
        {% csrf_token %}
        {{ recommendation_form.as_p }}
        <button type="submit" name="submit_recommendation">Pošalji preporuku</button>
    </form>

    <br>
    <hr>
    
</body>
</html>